#Translators MySQL BASE
#Set base image
FROM store/oracle/mysql-enterprise-server:5.7

#Dockerfile Author / Maintainer
MAINTAINER 					Name TonyCA911

#Environment variables
ENV MYSQL_USER trnsltr
ENV MYSQL_PASSWORD trnsltr911
ENV MYSQL_DATABASE TRANSLATORS_DB